print("My name is Becca")
print("My name is Monica")
print("Helloooo")
print("I was born in Nebraska")
print('My favorite food is dark chocolate')
print('My favorite type of music is pop')
print('My astrological sign is aries')
print('My moms maiden name is Joffe')
