print("My name is Becca")
print("My name is Monica")
print("Helloooo")
print("I was born in Nebraska")
print("I like pizza and sushi")
print("I like all types of music")
print("I am a piscies")
print("My mothers maiden name is Ketelhut")
